config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :courses
  resources :users, only: %i[index edit show update]

  root 'static_pages#landing_page'

  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'activity', to: 'static_pages#activity'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  include PublicActivity::Model
  tracked owner: Proc.new{ |controller, model| controller.current_user}

  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, :short_description, :language, :price, :level, presence: true
  validates :description, presence: true, length: { minimum: 5 }

  has_rich_text :description

  belongs_to :user

  def to_s
    title
  end

  LANGUAGES = [:"English", :"Russian", :"Polish"]

  def self.languages
    LANGUAGES.map { |lang| [lang, lang] }
  end

  LEVELS = [:"Beginner", :"Intermediate", :"Advanced"]

  def self.levels
    LEVELS.map { |lvl| [lvl, lvl] }
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  validates :name, presence: true, uniqueness: true
  scopify
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  rolify

  extend FriendlyId
  friendly_id :email, use: :slugged

  has_many :courses

  validate :must_have_a_role, on: :update

  after_create :assign_default_role

  def to_s
    email
  end

  def username
    self.email.split(/@/).first
  end

  def assign_default_role
    if User.count == 1
      self.add_role(:admin) if self.roles.blank?
      self.add_role(:teacher)
      self.add_role(:student)
    else
      self.add_role(:student) if self.roles.blank?
      self.add_role(:teacher)
    end
  end

  def online?
    updated_at > 2.minutes.ago
  end

  private

  def must_have_a_role
    unless roles.any?
      errors.add(:roles, "must have at least one role")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include PublicActivity::StoreController
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  before_action :authenticate_user!
  before_action :set_global_variables, if: :user_signed_in?
  after_action :user_activity

  def set_global_variables
    @ransack_courses = Course.ransack(params[:courses_search], search_key: :courses_search)
  end

  private

  def user_not_authorized #pundit
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end

  def user_activity
    current_user&.touch
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  def index
    @ransack_courses = Course.ransack(params[:courses_search], search_key: :courses_search)
    @courses = @ransack_courses.result.includes(:user)
  end

  def show
  end

  def new
    @course = Course.new
    authorize @course
  end

  def edit
    authorize @course
  end

  def create
    @course = Course.new(course_params)
    authorize @course
    @course.user = current_user

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @course
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @course
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_course
    @course = Course.friendly.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :description, :short_description, :price, :language, :level)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[landing_page]

  def landing_page
    @courses = Course.all.limit(3)
    @latest_courses = Course.all.limit(3).order(created_at: :desc)
  end

  def activity
    @activities = PublicActivity::Activity.all
  end

  def privacy_policy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update]

  def index
    @users = User.all.order(created_at: :desc)
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true)
  end

  def show
  end

  def edit
    authorize @user
  end

  def update
    authorize @user
    if @user.update(user_params)
      redirect_to users_path, notice: "User #{@user.email} was successfully updated"
    end
  end

  private

  def set_user
    @user = User.friendly.find(params[:id])
  end

  def user_params
    params.require(:user).permit({ role_ids: [] })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/courses/_course.html.erb
<div class="col-md-4 mb-3">
  <div class="card text-white card-has-bg click-col" style="background-image:url('https://source.unsplash.com/600x900/?tech,street');">
    <img alt="Goverment Lorem Ipsum Sit Amet Consectetur dipisi?" class="card-img d-none" src="https://source.unsplash.com/600x900/?tech,street"/>
    <div class="card-img-overlay d-flex flex-column">
      <div class="card-body">
        <h5 class="card-meta">
          <div class="fa fa-graduation-cap"></div>
          <%= link_to course.title, course_path(course), style: 'color:white; text-decoration:none;' %>
        </h5>
        <hr/>
        <small class="card-title">
          <span class="text-white">
            <%= course.short_description %>
          </span>
        </small>
      </div>

      <div class="card-footer">
        <div class="d-flex justify-content-between">
          <div>
            <i class="fa fa-signal"></i>
            <%= course.level %>
          </div>
          <div>
            <i class="fa fa-globe-africa"></i>
            <%= course.language %>
          </div>
          <div class="">
            <%= number_to_currency(course.price) %>
          </div>
        </div>
      </div>

      <div class="card-footer">
        <hr>
        <div class="media-body">
          <div class="d-flex justify-content-around">
            <small>
              <div class="far fa-clock mb-2"></div>
              <%= course.created_at.strftime('%d-%b-%Y') %>
            </small>

            <small>
              <div class="fa fa-chalkboard-teacher"></div>
              <%= course.user.username %>
            </small>
          </div>
        </div>
        <hr/>
        <div class="d-flex justify-content-around">
          <% if policy(course).edit? %>
            <%= button_to edit_course_path(course), class: 'btn btn-primary btn-circle btn-circle-sm m-1', method: :get do %>
              <i class="fa fa-pen"></i>
            <% end %>
            <%= button_to course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-circle btn-circle-sm m-1' do %>
              <i class="fa fa-trash"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/courses/_form.html.erb
<div class="container">
  <%= simple_form_for(@course) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <div class="form-inputs">
      <%= f.input :title %>
      <%= f.label :description %>
      <%= f.rich_text_area :description %>
      <small>
        <%= f.error :description, class: 'text-danger' %>
      </small>
      <%= f.input :short_description %>
      <%= f.input :language, collection: Course.languages, include_blank: true %>
      <%= f.input :level, collection: Course.levels, include_blank: true %>
      <%= f.input :price %>
    </div>
    <div class="form-actions mt-5">
      <%= f.button :submit, class: 'btn btn-success' %>
    </div>
    <%= button_to 'Back', courses_path, class: 'btn btn-primary mt-3' %>
  <% end %>
</div>

app/views/courses/edit.html.erb
<div class="card mt-4">
  <div class="card-header">
    <h1>Editing course</h1>
  </div>
  <div class="card-body mt-4">
    <%= render 'form' %>
  </div>
</div>

app/views/courses/index.html.erb
<div class="text-center mb-4">
  <h3>Courses
    <span class="badge bg-info">
      <%= @courses.count %>
    </span>
  </h3>
</div>

<section class="wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-2">
        <%= search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f| %>
          <%= f.label :title %>
          <%= f.search_field :title_cont, placeholder: 'title', class: 'form-control form-control-sm' %>
          <%= f.label :description %>
          <%= f.search_field :short_description_cont, placeholder: 'short_descr', class: 'form-control form-control-sm' %>
          <%= f.label :language %>
          <%= f.select :language_cont, Course.languages, include_blank: true %>
          <%= f.label :level %>
          <%= f.select :level_cont, Course.levels, include_blank: true %>
          <%= f.label :price %>
          <%= f.search_field :price_eq, placeholder: 'price', class: 'form-control form-control-sm' %>
          <%= f.label :teacher %>
          <%= f.search_field :user_email_cont, placeholder: 'email', class: 'form-control form-control-sm' %>
          <%= f.submit %>
          <%= link_to courses_path, class: 'btn btn-secondary', style: 'vertical-align: baseline;' do %>
            <i class="fas fa-sync"></i>
          <% end %>
        <% end %>
      </div>
      <div class="col-md-10">
        <div class="row">
          <% @courses.each do |course| %>
            <%= render 'courses/course', course: course %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/courses/new.html.erb
<div class="card">
  <div class="card-header">
    <h1>New course</h1>
  </div>
  <div class="card-body mt-4">
    <%= render 'form' %>
  </div>
</div>

app/views/courses/show.html.erb
<div class="row justify-content-center">
  <div class="mb-3">
    <%= link_to 'Courses', course_path %> \
    <%= link_to @course.title, course_path(@course) %>
  </div>
  <%= render 'courses/course', course: @course %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <title>Mvp2021</title>
    <meta content="width=device-width,initial-scale=1" name="viewport"/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'shared/notifications' %>
    <%= render 'shared/navbar' %>
    <div class="container">
      <p></p>
      <%= yield %>
    </div>
    <div class="bg-light">
      <%= render 'shared/footer'%>
    </div>
  </body>
</html>

app/views/shared/_footer.html.erb
<hr/>
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        Copyright <i class="fa fa-copyright"></i>
        <%= Time.now.year %>
        CoursePlatform Sp. z o.o.
        <div class="row"></div>
        <div class="fa fa-envelope"></div>
        <%= mail_to 'contact@me.com' %>
        <div class="row"></div>
      </div>
      <div class="col-md-4">
        Privacy policy
        <div class="row"></div>
        Terms and conditions
      </div>
      <div class="col-md-4">
        About us
        <div class="row"></div>
        <%= link_to 'Teach on CoursePlatform', new_course_path %>
      </div>
    </div>
  </div>
</footer>
<br/>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">MVP-2021</a>
    <button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-bs-target="#navbarSupportedContent" data-bs-toggle="collapse" type="button">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if current_user %>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="<%= 'active font-weight-bold' if current_page?(root_path) %> nav-item">
            <%= link_to root_path, class: 'nav-link' do %>
              <div class="fa fa-home"></div>
              Home
            <% end %>
          </li>
          <li class="<%= 'active font-weight-bold' if current_page?(courses_path) %> nav-item">
            <%= link_to courses_path, class: 'nav-link' do %>
              <div class="fa fa-book"></div>
              Courses
            <% end %>
          </li>
          <li class="<%= 'active font-weight-bold' if current_page?(courses_path) %> nav-item">
            <%= link_to new_course_path, class: 'nav-link' do %>
              <div class="fa fa-plus"></div>
              New Course
            <% end %>
          </li>
          <li class="<%= 'active font-weight-bold' if current_page?(users_path) %> nav-item">
            <%= link_to users_path, class: 'nav-link' do %>
              <div class="fas fa-users"></div>
              Users
            <% end %>
          </li>
        </ul>

        <div class="form d-flex h-100">
          <%= search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f| %>
            <div class="searchbar">
              <%= f.search_field :title_cont, autocomplete: 'off', placeholder: "Search...", class: 'search_input' %>
              <button class="search_icon" type="submit">
                <span class="fa fa-search"></span>
              </button>
            </div>
          <% end %>
        </div>
        <ul class="navbar-nav mb-2 mb-lg-0">
          <li class="<%= 'active font-weight-bold' if current_page?(activity_path) %> nav-item">
            <%= link_to activity_path, class: 'nav-link' do %>
              <div class="fas fa-bell"></div>
              Activity
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <a aria-expanded="false" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" id="navbarDropdown" role="button">
              <b>
                <%= current_user.email %>
              </b>
            </a>
            <div aria-labelledby="navbarDropdown" class="dropdown-menu">
              <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
                <div class="fa fa-cog">
                  <b>Account settings</b>
                </div>
              <% end %>
              <%= link_to privacy_policy_path, class: "dropdown-item" do %>
                <div class="fas fa-file-word">
                  <b>Privacy Policy</b>
                </div>
              <% end %>
              <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
                <div class="fa fa-sign-out-alt">
                  <b>Sign out</b>
                </div>
              <% end %>
            </div>
          </li>
        </ul>
      <% else %>
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Log In', new_user_session_path, class: 'nav-link' %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_notifications.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div aria-atomic="true" aria-live="assertive" class="position-relative">
      <div class="toast-body position-absolute top-0 end-0" style="z-index: 5">
        <div class="alert alert-dismissible fade show alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
          <div aria-hidden="true" aria-label="Close" class="btn-close btn-sm" data-bs-dismiss="alert" type="button"></div>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/static_pages/activity.html.erb
<div class="text-center mb-4">
  <h3>Activity
    <span class="badge bg-info">
      <%= @activities.count %>
    </span>
  </h3>
</div>

<ul class="list-group">
  <% @activities.each do |activity| %>
    <li class="list-group-item">
      <%= activity.id %>
      <%= activity.trackable_type %>
      <%= activity.trackable_id %>
      <%= link_to activity.trackable, activity.trackable %>
      <%= activity.key %>
      <%= activity.parameters %>
      <%= activity.owner %>
    </li>
  <% end %>
</ul>

app/views/static_pages/landing_page.html.erb
<div class="card jumbotron" style="min-height: 150px;">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="text-center">
        <span class="display-5">What do you want to learn today?</span>
        <% if current_user %>
          <div class="form h-100 justify-content-center mt-3">
            <%= search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f| %>
              <div class="searchbar">
                <%= f.search_field :title_cont, autocomplete: 'off', placeholder: "Search...", class: 'search_input' %>
                <button class="search_icon" type="submit">
                  <span class="fa fa-search"></span>
                </button>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="card-group">
  <div class="card card-body shadow-sm border" style="min-height: 150px;">
    <h1>
      <i class="fa fa-graduation-cap"></i>
    </h1>
    <%= Course.count %>
    online courses
    <div class="row"></div>
    Explore a variety of fresh topics
  </div>

  <div class="card card-body shadow-sm border" style="min-height: 150px;">
    <h1>
      <i class="fa fa-chalkboard-teacher">
        <!--.fa.fa-brain
        -->
      </i>
    </h1>
    <%= Course.distinct.count(:user_id) %>
    expert instructors
    <div class="row"></div>
    Find the right instructor for you
  </div>

  <div class="card card-body shadow-sm border" style="min-height: 150px;">
    <h1>
      <i class="fa fa-user-graduate"></i>
    </h1>
    <%= User.count %>
    active learners
    <div class="row"></div>
    Join the knowledge sharing community
  </div>

  <div class="card card-body shadow-sm border" style="min-height: 150px;">
    <h1>
      <i class="fa fa-infinity"></i>
    </h1>
    Lifetime access
    <div class="row"></div>
    Learn on your schedule
  </div>
</div>


<hr>
<h2>
  Popular courses
</h2>
<div class="wrapper">
  <div class="container">
    <div class="row m-5">
      <% @courses.each do |course| %>
        <%= render 'courses/course', course: course %>
      <% end %>
    </div>
  </div>
</div>
<hr>
<h2>
  Top rated courses
</h2>
<div class="wrapper">
  <div class="container">
    <div class="row m-5">
      <% @courses.each do |course| %>
        <%= render 'courses/course', course: course %>
      <% end %>
    </div>
  </div>
</div>
<hr>
<h2>
  Latest courses
</h2>
<div class="wrapper">
  <div class="container">
    <div class="row m-5">
      <% @latest_courses.each do |course| %>
        <%= render 'courses/course', course: course %>
      <% end %>
    </div>
  </div>
</div>

app/views/static_pages/privacy_policy.html.erb
<h1>Privacy Policy</h1>
<%= link_to "Home", root_path %>

app/views/users/_user.html.erb
<div class="col-md-3">
  <div class="card text-center mb-3" style="width: 18rem; min-height: 24rem">
    <div class="card-header bg-info" style="text-align: center;">
      <% if user.online? %>
        <i class="fa fa-circle text-success"></i>
      <% else %>
        <i class="fa fa-circle text-danger"></i>
      <% end %>

      <i class="fa fa-user"></i>
      <%= link_to user.email, user_path(user) %>
    </div>

    <div class="card-footer bg-light">
      <div class="card-text">
        Signed up <%= time_ago_in_words(user.created_at) %> ago
        <p>
          <%= 'sign_in_count'.humanize %>:
          <%= user.sign_in_count %>
        </p>
        <p>
          <%= 'current_sign_in_at'.humanize %>: <br>
          <%= user.current_sign_in_at %>
        </p>
        <p>
          <%= 'last_sign_in_at'.humanize %>: <br>
          <%= user.last_sign_in_at %>
        </p>
        <p>
          <%= 'current_sign_in_ip'.humanize %>: <br>
          <%= user.current_sign_in_ip %>
        </p>
        <p>
          <%= 'last_sign_in_ip'.humanize %>: <br>
          <%= user.last_sign_in_ip %>
        </p>
      </div>
    </div>
    <div class="card-footer bg-light">
      <div class="card-text">
        <% user.roles.each do |role| %>
          <div class="badge bg-info">
            <%= role.name %>
          </div>
        <% end %>
        <% if policy(user).edit? %>
          <%= link_to 'Edit roles', edit_user_path(user), class: 'btn badge bg-warning' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="card">
  <div class="card-header">
    <h3>Editing roles for <%= @user.email %></h3>
  </div>
  <div class="card-body">
    <%= simple_form_for @user do |f| %>
      <%= f.collection_check_boxes :role_ids, Role.all, :id, :name %>
      <%= f.error :roles, class: 'text-danger' %>
      <hr/>
      <%= f.button :submit, class: "btn btn-success" %>
    <% end %>
  </div>
  <div class="card-footer">
    <%= link_to 'Cancel', users_path, class: 'btn btn-danger' %>
  </div>
</div>

app/views/users/index.html.erb
<div class="text-center mb-4">
  <h3>Users
    <span class="badge bg-info">
      <%= @users.count %>
    </span>
  </h3>
</div>

<div class="row justify-content-center">
  <% @users.each do |user| %>
    <%= render 'users/user', user: user %>
  <% end %>
</div>

<div class="form-inline d-flex justify-content-center">
  <%= search_form_for @q do |f| %>
    <%= link_to users_path, class: 'btn btn-secondary', style: 'vertical-align: baseline;' do %>
      <i class="fas fa-sync"></i>
    <% end %>
    <%= f.search_field :email_cont, placeholder: 'email' %>
    <%= f.search_field :sign_in_count_eq, placeholder: 'sign in count' %>
    <%= f.search_field :email_or_sign_in_count_eq, placeholder: 'email or sign in count' %>
    <%= f.submit %>
  <% end %>
</div>
<div class="mt-3">
  <table class="table table-bordered">
    <thead>
    <tr>
      <th>id</th>
      <th>
        <%= sort_link(@q, :email) %>
      </th>
      <th>created_at</th>
      <th>
        <%= 'sign_in_count'.humanize %>
      </th>
      <th>
        <%= 'current_sign_in_at'.humanize %>
      </th>
      <th>
        <%= 'last_sign_in_at'.humanize %>
      </th>
      <th>
        <%= 'current_sign_in_ip'.humanize %>
      </th>
      <th>
        <%= 'last_sign_in_ip'.humanize %>
      </th>
    </tr>
    </thead>

    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= user.id %>
        </td>
        <td>
          <%= user.email %>
        </td>
        <td>
          <%= user.created_at %>
        </td>
        <td>
          <%= user.sign_in_count %>
        </td>
        <td>
          <%= user.current_sign_in_at %>
        </td>
        <td>
          <%= user.last_sign_in_at %>
        </td>
        <td>
          <%= user.current_sign_in_ip %>
        </td>
        <td>
          <%= user.last_sign_in_ip %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<div class="row justify-content-center">
  <%= render 'users/user', user: @user %>
</div>